return {
  "LudoPinelli/comment-box.nvim",
  lazy = true,
  cmd = {
    "CBllbox",
    "CBlcbox",
    "CBlrbox",
    "CBclbox",
    "CBccbox",
    "CBcrbox",
    "CBrlbox",
    "CBrcbox",
    "CBrrbox",
    "CBlabox",
    "CBbcaox",
    "CBrabox",
    "CBllline",
    "CBlcline",
    "CBlrline",
    "CBclline",
    "CBccline",
    "CBcrline",
    "CBrlline",
    "CBrcline",
    "CBrrline",
    "CBcatalog",
  },
}
