tap "daipeihust/tap"
tap "gambithunt/tools"
tap "homebrew/bundle"
tap "koekeishiya/formulae"
tap "laishulu/homebrew"
tap "nikitabobko/tap"
# GNU debugger for arm-none-eabi cross development
brew "arm-none-eabi-gdb"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# GNU Emacs text editor
brew "emacs"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Plugin manager for the Fish shell
brew "fisher"
# Terminal JSON viewer
brew "fx"
# Command-line fuzzy finder written in Go
brew "fzf"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Render markdown on the CLI
brew "glow"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Manage your GnuPG keys with ease!
brew "gpg-tui"
# Command-line hex viewer
brew "hexyl"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Simple terminal UI for git commands
brew "lazygit"
# Package manager for the Lua programming language
brew "luarocks"
# Language Server Protocol for Markdown
brew "marksman"
# Unified display of technical and tag data for audio/video
brew "media-info"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Media player based on MPlayer and mplayer2
brew "mpv"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Command-line Git information tool
brew "onefetch"
# On-chip debugging, in-system programming and boundary-scan testing
brew "open-ocd"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Paste PNG into files
brew "pngpaste"
# Modern replacement for ps written in Rust
brew "procs"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Cross-shell prompt for astronauts
brew "starship"
# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# General purpose fuzzy finder TUI
brew "television"
# Terminal multiplexer
brew "tmux"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# macOS Input Source Manager
brew "laishulu/homebrew/macism"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Continuation of Clash Verge - A Clash Meta GUI based on Tauri
cask "clash-verge-rev"
cask "font-maple-mono-nf-cn"
cask "font-sf-mono"
cask "font-sf-pro"
# Pre-built GNU bare-metal toolchain for 32-bit Arm processors
cask "gcc-arm-embedded"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Desktop client for GitHub repositories
cask "github"
# GPU-based terminal emulator
cask "kitty"
# Neovim Client
cask "neovide-app"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Control your tools with a few keystrokes
cask "raycast"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Gecko based web browser
cask "zen"
cargo "cargo-expand"
cargo "cargo-nextest"
cargo "cmd-wrapped"
